apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: firefox-grid
  name: firefox-grid
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
    - name: "7900"
      port: 7900
      targetPort: 7900
    # - name : "7900"
    #   port: 7900
    #   targetPort: 7900
  selector:
    app: firefox-grid
status:
  loadBalancer: {}
