apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: novel-crawler-kt
  name: novel-crawler-kt
  namespace: default
spec:
  # ports:
  #   - name: "5432"
  #     port: 5432
  #     targetPort: 5432
  selector:
    app: novel-crawler-kt
status:
  loadBalancer: {}
